"""Schema definitions and validation helpers for AI-generated practice data."""
from typing import Any, Dict, List


BLOCK_SCHEMA = {
    "required": ["drill_id", "drill_name", "block_type", "allocated_time"],
    "fields": {
        "drill_id": str,
        "drill_name": str,
        "block_type": str,
        "allocated_time": int,
        "category": str,
        "intensity": str,
        "players_min": int,
        "players_max": int,
        "diagram_path": (str, type(None)),
    },
}

SESSION_SCHEMA = {
    "required": ["team_id", "team_name", "session_date", "duration_minutes", "drills"],
    "fields": {
        "team_id": str,
        "team_name": str,
        "session_date": str,
        "duration_minutes": int,
        "num_players": int,
        "selected_categories": list,
        "drills": list,
        "notes": (str, type(None)),
    },
}


def _ensure_field(name: str, value: Any, expected_type) -> str:
    if value is None:
        return f"Field '{name}' is required."
    if isinstance(expected_type, tuple):
        if not isinstance(value, expected_type):
            return f"Field '{name}' must be one of types: {expected_type}."
        return ""
    if expected_type is list:
        if not isinstance(value, list):
            return f"Field '{name}' must be a list."
    elif expected_type is int:
        try:
            int(value)
        except Exception:
            return f"Field '{name}' must be an integer."
    elif not isinstance(value, expected_type):
        return f"Field '{name}' must be {expected_type.__name__}."
    return ""


def validate_ai_output(json_data: Dict[str, Any]) -> bool:
    """
    Validate a practice session or cycle payload generated by an AI step.

    Raises ValueError with descriptive message on failure.
    """
    errors: List[str] = []
    if not isinstance(json_data, dict):
        raise ValueError("AI output must be a JSON object.")

    for field in SESSION_SCHEMA["required"]:
        if field not in json_data:
            errors.append(f"Missing required field '{field}'.")

    for field, expected in SESSION_SCHEMA["fields"].items():
        if field in json_data:
            msg = _ensure_field(field, json_data[field], expected)
            if msg:
                errors.append(msg)

    drills = json_data.get("drills")
    if drills is None or not isinstance(drills, list) or len(drills) == 0:
        errors.append("Drills array is required and must be non-empty.")
    else:
        for idx, drill in enumerate(drills, start=1):
            if not isinstance(drill, dict):
                errors.append(f"Drill {idx} must be an object.")
                continue
            for req in BLOCK_SCHEMA["required"]:
                if req not in drill or drill[req] in ("", None):
                    errors.append(f"Drill {idx} missing required field '{req}'.")
            for field, expected in BLOCK_SCHEMA["fields"].items():
                if field in drill:
                    msg = _ensure_field(field, drill[field], expected)
                    if msg:
                        errors.append(f"Drill {idx}: {msg}")

    if errors:
        message = " ".join(errors)
        raise ValueError(message)
    return True
