from pathlib import Path
path = Path('pages/3_Practice_History.py')
lines = path.read_text(encoding='utf-8').splitlines()
start = end = None
for i, l in enumerate(lines):
    if start is None and l.strip() == 'st.subheader("Timeline")':
        start = i
    if start is not None and end is None and l.strip() == 'st.divider()' and i + 1 < len(lines) and lines[i+1].lstrip().startswith('if is_dev'):
        end = i
if start is None or end is None:
    raise SystemExit('markers not found')

new_block = [
    'st.subheader("Timeline")',
    'if len(display_df) == 0:',
    '    st.info("No sessions for this time window. Try expanding your filters.")',
    'else:',
    '    if time_window == "This week":',
    '        timeline_label = "This Week"',
    '    elif time_window == "Last 30 days":',
    '        timeline_label = "Last 30 days"',
    '    else:',
    '        timeline_label = "All time"',
    '',
    '    st.markdown(f"### {timeline_label}")',
    '',
    '    for idx, session_row in display_df.iterrows():',
    '        session_date = session_row.get("date_norm")',
    '        session_name = session_row.get("session_name") or "Practice"',
    '        total_time = session_row.get("total_time", 0)',
    '        categories = session_row.get("categories", "")',
    '        num_players = session_row.get("num_players", 0)',
    '        is_favorite = bool(session_row.get("is_favorite", False))',
    '        coach_notes = str(session_row.get("coach_notes", "") or "").strip()',
    '        intensity_level = session_row.get("intensity_level", "") or ""',
    '        intensity_score = session_row.get("avg_intensity_score", None)',
    '',
    '        with st.container():',
    '            main_cols = st.columns([0.5, 5, 1.5])',
    '',
    '            with main_cols[0]:',
    '                star_label = "★" if is_favorite else "☆"',
    '                if st.button(star_label, key=f"star_{idx}", help="Add to Practice Library"):',
    '                    success = practice_history.set_session_favorite(',
    '                        team_id,',
    '                        session_date,',
    '                        session_name,',
    '                        not is_favorite,',
    '                        st.session_state.data_path,',
    '                    )',
    '                    if success:',
    '                        st.rerun()',
    '',
    '            with main_cols[1]:',
    '                st.markdown(f"**{session_date} — {session_name} ({total_time} min)**")',
    '                if intensity_level and intensity_score is not None and not pd.isna(intensity_score):',
    '                    intensity_str = f" · Intensity: {intensity_level} ({intensity_score:.1f})"',
    '                elif intensity_level:',
    '                    intensity_str = f" · Intensity: {intensity_level}"',
    '                else:',
    '                    intensity_str = ""',
    '                st.caption(f"Categories: {categories or '"'"'—'"'"'} | Players: {num_players}{intensity_str}")',
    '',
    '                if coach_notes:',
    '                    preview = coach_notes[:80] + ("..." if len(coach_notes) > 80 else "")',
    '                    st.caption(f"📝 {preview}")',
    '',
    '            with main_cols[2]:',
    '                if not is_favorite:',
    '                    if st.button("Add to Practice Library", key=f"fav_{idx}", type="primary"):',
    '                        success = practice_history.set_session_favorite(',
    '                            team_id,',
    '                            session_date,',
    '                            session_name,',
    '                            True,',
    '                            st.session_state.data_path,',
    '                        )',
    '                        if success:',
    '                            st.success("Added to Practice Library")',
    '                            st.rerun()',
    '                        else:',
    '                            st.error("Could not add to Practice Library")',
    '                else:',
    '                    if st.button("Remove from Library", key=f"unfav_{idx}", type="secondary"):',
    '                        success = practice_history.set_session_favorite(',
    '                            team_id,',
    '                            session_date,',
    '                            session_name,',
    '                            False,',
    '                            st.session_state.data_path,',
    '                        )',
    '                        if success:',
    '                            st.success("Removed from Practice Library")',
    '                            st.rerun()',
    '                        else:',
    '                            st.error("Could not update Practice Library")',
    '',
    '                if st.button("View Details", key=f"view_{idx}"):',
    '                    st.session_state["viewing_session"] = session_row.to_dict()',
    '                    st.rerun()',
    '                if st.button("Reuse session", key=f"reuse_{idx}", type="secondary"):',
    '                    session_structure = session_row.get("session_structure", "")',
    '                    if session_structure:',
    '                        try:',
    '                            data = json.loads(session_structure)',
    '                            drills = [SessionDrill.from_dict(d) for d in data.get("drills", [])]',
    '                            cfg_dict = data.get("config", {})',
    '                            config_obj = PracticeConfig(**cfg_dict) if cfg_dict else PracticeConfig(',
    '                                duration_minutes=data.get("duration_minutes", 90),',
    '                                num_players=data.get("num_players", 16),',
    '                                num_drills=len(drills),',
    '                                selected_categories=data.get("selected_categories", []),',
    '                                session_date=str(session_date),',
    '                                session_notes=data.get("session_notes", ""),',
    '                            )',
    '                            session_obj = PracticeSession(',
    '                                session_id=data.get("session_id", "reuse"),',
    '                                team_id=data.get("team_id", team_id),',
    '                                team_name=data.get("team_name", team.get("team_name", "")),',
    '                                session_date=data.get("session_date", str(session_date)),',
    '                                config=config_obj,',
    '                                duration_minutes=data.get("duration_minutes", config_obj.duration_minutes),',
    '                                num_players=data.get("num_players", config_obj.num_players),',
    '                                num_drills=len(drills),',
    '                                selected_categories=data.get("selected_categories", config_obj.selected_categories),',
    '                                drills=drills,',
    '                                team_profile_summary=data.get("team_profile_summary", {}),',
    '                                equipment_needed=data.get("equipment_needed", []),',
    '                                category_summary=data.get("category_summary", {}),',
    '                                intensity_summary=data.get("intensity_summary", {}),',
    '                            )',
    '                            st.session_state.current_session = session_obj',
    '                        except Exception:',
    '                            st.session_state.current_session = None',
    '                    else:',
    '                        ui_session.set_practice_config(',
    '                            duration_minutes=total_time or 90,',
    '                            num_players=num_players or 16,',
    '                            num_drills=5,',
    '                            selected_categories=[c.strip() for c in str(categories).split("|") if c.strip()],',
    '                            session_notes=str(session_row.get("session_notes", "") or ""),',
    '                        )',
    '                        st.session_state.current_session = None',
    '                    st.switch_page("pages/2_Practice_Generator.py")',
    '',
    '        with st.expander("Session Notes", expanded=False):',
    '            notes_value = st.text_area(',
    '                "What did you notice in this session?",',
    '                value=coach_notes,',
    '                key=f"notes_{idx}",',
    '                height=100,',
    '                help="Add observations, what worked well, areas for improvement, etc.",',
    '            )',
    '',
    '            col_save, col_cancel = st.columns([1, 3])',
    '            with col_save:',
    '                if st.button("Save Notes", key=f"save_notes_{idx}"):',
    '                    success = practice_history.update_session_notes(',
    '                        team_id,',
    '                        session_date,',
    '                        session_name,',
    '                        notes_value,',
    '                        st.session_state.data_path,',
    '                    )',
    '                    if success:',
    '                        st.success("Notes saved!")',
    '                        st.rerun()',
    '                    else:',
    '                        st.error("Failed to save notes")',
    '',
    '        st.divider()',
    'st.divider()',
]

new_lines = lines[:start] + new_block + lines[end+1:]
path.write_text('\n'.join(new_lines) + '\n', encoding='utf-8')
