import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy — Footy Mentor',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background px-4 py-12">
      <div className="max-w-3xl mx-auto space-y-10">

        {/* Header */}
        <div className="space-y-2">
          <Link href="/login" className="text-xs text-muted-foreground hover:text-primary transition-colors">
            ← Back to Sign In
          </Link>
          <h1 className="text-3xl font-black text-white tracking-tight mt-4">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground">
            Last updated: June 21, 2026 &nbsp;·&nbsp; Effective: June 21, 2026
          </p>
        </div>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-muted-foreground leading-relaxed">

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">1. Overview</h2>
            <p>
              Footy Mentor (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) is committed to protecting
              your personal information. This Privacy Policy explains what data we collect, how we use it,
              who we share it with, and what rights you have over it.
            </p>
            <p>
              This policy applies to all users of the Footy Mentor website and application (the &ldquo;Service&rdquo;).
              By using the Service, you agree to the collection and use of your data as described here.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">2. What We Collect</h2>

            <h3 className="text-base font-semibold text-foreground">2a. Information You Provide Directly</h3>
            <p>When you create an account and complete your player profile, we collect:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li><strong className="text-foreground">Account credentials:</strong> Username and hashed password (we never store your password in plain text), or a Google account identifier if you sign in with Google</li>
              <li><strong className="text-foreground">Contact information:</strong> Email address</li>
              <li><strong className="text-foreground">Player profile:</strong> Full name, age, gender, primary and secondary position, preferred foot, age group</li>
              <li><strong className="text-foreground">Playing background:</strong> Current playing level (recreational through professional), league/club, target level, graduation year</li>
              <li><strong className="text-foreground">Training preferences:</strong> Sessions per week, session duration, focus areas, available equipment</li>
              <li><strong className="text-foreground">Academic information (optional):</strong> GPA and scale, ACT score, SAT score — provided voluntarily and used only to personalize AI-drafted recruiting emails</li>
              <li><strong className="text-foreground">Video content:</strong> Highlight clips you upload for coaching review (up to 50 MB per file)</li>
              <li><strong className="text-foreground">Recruiting questions:</strong> Questions you submit alongside video clips for coach review</li>
              <li><strong className="text-foreground">Program interest notes:</strong> Text you enter when drafting recruiting emails</li>
            </ul>

            <h3 className="text-base font-semibold text-foreground mt-4">2b. Information Generated by Your Use</h3>
            <p>As you use the Service, we automatically generate and store:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li><strong className="text-foreground">Training activity:</strong> Which sessions you complete, which drills you log, and the dates of each</li>
              <li><strong className="text-foreground">RRS history:</strong> Your weekly Readiness &amp; Reliability Score snapshots and pillar breakdowns (consistency, volume, coverage, progression)</li>
              <li><strong className="text-foreground">Training plans:</strong> Your weekly and multi-week personalized training plans</li>
            </ul>

            <h3 className="text-base font-semibold text-foreground mt-4">2c. Automatically Collected Technical Data</h3>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li><strong className="text-foreground">Session cookie:</strong> An encrypted session cookie that keeps you logged in. It stores only your username and expiration time — not browsing behavior.</li>
              <li><strong className="text-foreground">Server logs:</strong> Standard web server logs (IP address, request path, timestamp) retained for security monitoring. We do not use IP addresses to build advertising profiles.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">3. How We Use Your Data</h2>
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="border-b border-border/40">
                  <th className="text-left py-2 pr-4 text-foreground font-semibold w-2/5">Purpose</th>
                  <th className="text-left py-2 text-foreground font-semibold">Data Used</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/20">
                <tr>
                  <td className="py-2.5 pr-4 align-top">Generate your training plan</td>
                  <td className="py-2.5 align-top">Position, level, focus areas, sessions per week, equipment, training history</td>
                </tr>
                <tr>
                  <td className="py-2.5 pr-4 align-top">Calculate your RRS score</td>
                  <td className="py-2.5 align-top">Completion log, training plan, dates of activity</td>
                </tr>
                <tr>
                  <td className="py-2.5 pr-4 align-top">Deliver coaching feedback on your reel</td>
                  <td className="py-2.5 align-top">Video clips, review question, username</td>
                </tr>
                <tr>
                  <td className="py-2.5 pr-4 align-top">Draft recruiting emails via AI</td>
                  <td className="py-2.5 align-top">Name, position, level, graduation year, academic scores (if provided), program interest notes — sent to Anthropic&apos;s API</td>
                </tr>
                <tr>
                  <td className="py-2.5 pr-4 align-top">Send password reset emails</td>
                  <td className="py-2.5 align-top">Email address, username — sent via Resend</td>
                </tr>
                <tr>
                  <td className="py-2.5 pr-4 align-top">Send weekly training summaries (future)</td>
                  <td className="py-2.5 align-top">Email address, RRS data, session summary — sent via Resend</td>
                </tr>
                <tr>
                  <td className="py-2.5 pr-4 align-top">Prevent abuse</td>
                  <td className="py-2.5 align-top">Username, IP address, request timestamps — for rate limiting</td>
                </tr>
              </tbody>
            </table>
            <p className="text-xs mt-2">
              We do not use your data for advertising, and we do not sell your personal information to any third party.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">4. Third-Party Services We Use</h2>
            <p>
              We share limited data with the following third-party providers to operate the Service.
              Each is bound by their own privacy policy.
            </p>

            <div className="space-y-4 mt-2">
              <div className="border border-border/40 rounded-lg p-4 space-y-1">
                <p className="text-foreground font-semibold text-sm">Supabase</p>
                <p className="text-xs">Role: Database and file storage provider. Stores all user account data, training plans, completion logs, RRS history, and uploaded video clips. Data is hosted on infrastructure within the United States.</p>
                <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline">supabase.com/privacy</a>
              </div>

              <div className="border border-border/40 rounded-lg p-4 space-y-1">
                <p className="text-foreground font-semibold text-sm">Anthropic</p>
                <p className="text-xs">Role: AI model provider. When you use the recruiting email drafting feature, your name, position, level, graduation year, and any academic scores you&apos;ve entered are sent to Anthropic&apos;s API to generate a draft. Anthropic does not use API inputs from business customers to train their models.</p>
                <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline">anthropic.com/privacy</a>
              </div>

              <div className="border border-border/40 rounded-lg p-4 space-y-1">
                <p className="text-foreground font-semibold text-sm">Resend</p>
                <p className="text-xs">Role: Email delivery provider. Used to send password reset emails and (in future) weekly training summary emails. Your email address and username are shared with Resend when we send you an email.</p>
                <a href="https://resend.com/privacy" target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline">resend.com/privacy</a>
              </div>

              <div className="border border-border/40 rounded-lg p-4 space-y-1">
                <p className="text-foreground font-semibold text-sm">Google (OAuth)</p>
                <p className="text-xs">Role: Authentication provider (optional). If you choose &ldquo;Continue with Google,&rdquo; Google shares your name, email address, and a unique identifier with us. We use this to create or log in to your account. We do not receive your Google password.</p>
                <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline">policies.google.com/privacy</a>
              </div>

              <div className="border border-border/40 rounded-lg p-4 space-y-1">
                <p className="text-foreground font-semibold text-sm">Railway</p>
                <p className="text-xs">Role: Application hosting provider. The Footy Mentor application runs on Railway&apos;s infrastructure. Railway receives standard web traffic (IP addresses, request logs) as part of normal hosting operations.</p>
                <a href="https://railway.app/legal/privacy" target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline">railway.app/legal/privacy</a>
              </div>
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">5. Your Video Clips</h2>
            <p>
              Video clips you upload are stored in Supabase Storage. They are accessible only to:
            </p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>You (via a time-limited signed URL generated on your device)</li>
              <li>Our coaching staff, when you explicitly submit a clip for review</li>
            </ul>
            <p>
              Clips are not made public, shared with coaches listed in the Coach Finder, or used for
              any purpose other than providing you coaching feedback. If you delete a clip or delete
              your account, the file is removed from storage.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">6. Academic Data</h2>
            <p>
              Providing your GPA, ACT score, or SAT score is entirely optional. If you provide this
              information, it is stored in your profile and used only to personalize AI-drafted
              recruiting emails when you request them. It is not sold, shared with third parties
              for marketing, or used for any purpose beyond the recruiting email feature.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">7. Data Retention</h2>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li><strong className="text-foreground">Active accounts:</strong> We retain your data for as long as your account is active.</li>
              <li><strong className="text-foreground">Deleted accounts:</strong> When you delete your account, we delete your profile, training data, completion log, and all uploaded video clips within 30 days.</li>
              <li><strong className="text-foreground">Password reset tokens:</strong> Expire after 1 hour and are cleared from the database upon use or expiry.</li>
              <li><strong className="text-foreground">Server logs:</strong> Retained for up to 90 days for security purposes, then deleted.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">8. Your Rights</h2>
            <p>You have the right to:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li><strong className="text-foreground">Access:</strong> Request a copy of the personal data we hold about you</li>
              <li><strong className="text-foreground">Correction:</strong> Update your profile information at any time via your Profile page</li>
              <li><strong className="text-foreground">Deletion:</strong> Delete your account and all associated data from the &ldquo;Danger Zone&rdquo; section of your Profile page, or by contacting us</li>
              <li><strong className="text-foreground">Portability:</strong> Request your training data and profile in a machine-readable format</li>
              <li><strong className="text-foreground">Opt-out of emails:</strong> Password reset emails are transactional and cannot be opted out of while your account is active. If we introduce marketing or summary emails, you will be able to unsubscribe.</li>
            </ul>
            <p>
              To exercise any of these rights, contact us at <strong className="text-foreground">[YOUR CONTACT EMAIL]</strong>.
              We will respond within 30 days.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">9. Children&apos;s Privacy</h2>
            <p>
              Footy Mentor is not directed at children under 13. We do not knowingly collect personal
              information from children under 13. If you believe a child under 13 has provided us
              with personal information, please contact us and we will delete it promptly.
            </p>
            <p>
              Users between 13 and 17 should review this policy with a parent or guardian before
              using the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">10. Security</h2>
            <p>
              We take security seriously. Measures we have in place include:
            </p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Passwords are hashed using PBKDF2 with SHA-256 and a unique salt per user (600,000 iterations)</li>
              <li>All connections use HTTPS/TLS encryption in transit</li>
              <li>Session cookies are encrypted and HTTP-only</li>
              <li>Database access is restricted; unauthenticated requests cannot read user data</li>
              <li>Video file access uses time-limited signed URLs (1-hour expiry)</li>
              <li>Rate limiting is applied to all sensitive endpoints (login, signup, password reset, AI drafting)</li>
            </ul>
            <p>
              No system is 100% secure. If you discover a security vulnerability, please contact us
              at <strong className="text-foreground">[YOUR CONTACT EMAIL]</strong> before disclosing it publicly.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">11. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy to reflect changes to our data practices or for legal
              reasons. We will update the &ldquo;Last updated&rdquo; date at the top of this page and,
              for material changes, notify you by email (if on file) or by a notice within the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">12. Contact Us</h2>
            <p>
              For any questions about this Privacy Policy or to exercise your data rights:
            </p>
            <p className="text-foreground font-medium">
              [YOUR CONTACT EMAIL]
            </p>
            <p className="text-xs">
              We aim to respond to all privacy inquiries within 30 days.
            </p>
          </section>

        </div>

        {/* Footer links */}
        <div className="border-t border-border/30 pt-6 flex flex-wrap gap-4 text-xs text-muted-foreground">
          <Link href="/terms" className="hover:text-primary transition-colors">Terms of Service</Link>
          <Link href="/login" className="hover:text-primary transition-colors">Back to Sign In</Link>
        </div>

      </div>
    </div>
  );
}
