"""
Rebuild Drill Library - Individual Player Focus
Replaces team-level drills with individual development drills
a player can do solo or with one partner.

Run from the Coach AI root:
    python scripts/rebuild_drill_library.py
"""
import sys
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.append(str(ROOT / "src"))

DRILLS = [
    # WARMUP
    dict(drill_id="WARM_001", drill_name="Ball Mastery Warmup", category="Warmup",
         description="Activate your touch before every session. 8 minutes of continuous ball mastery in place: toe taps, inside-outside rolls, sole rolls, and figure-8s. Use both feet equally. Start slow, build pace over 4 minutes.",
         players_min=1, players_max=1, duration_minutes=8, field_type="Any",
         setup_data="Stand in place. Any surface works.", equipment="Ball",
         coaching_points="Keep eyes up as much as possible. Use both feet equally. Stay on your toes.",
         difficulty="beginner", intensity="low", coach_rating=5,
         solo_possible=True, min_equipment="Ball only",
         game_application="Ball mastery activates touch that translates directly to your first contact in a match. Players with consistent ball mastery make fewer mistakes in the opening minutes when the game is fastest.",
         coaching_cues="Stay on your toes|Eyes up not at the ball|Equal time on both feet|Relax your ankles|Small sharp touches",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Foundation Warmup", series_order=1, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="ball masury|warmup|both feet|technical", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="WARM_002", drill_name="Dynamic Movement Activation", category="Warmup",
         description="Progressive movement warmup over 20 meters: high knees, heel flicks, lateral shuffles, carioca, A-skips, then one sprint. Repeat twice. No ball required.",
         players_min=1, players_max=20, duration_minutes=8, field_type="Any",
         setup_data="20-meter straight line. Mark with cones or use field lines.", equipment="Cones",
         coaching_points="Arms drive the movement. Stay low on lateral shuffles. High knees above hip height.",
         difficulty="beginner", intensity="low", coach_rating=4,
         solo_possible=True, min_equipment="Ball only",
         game_application="Dynamic warmup reduces injury risk and prepares muscles for explosive movements in the first 10 minutes of a match.",
         coaching_cues="Drive arms to drive legs|Stay on balls of feet|Full range of motion|Gradually increase pace|Last rep is explosive",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Foundation Warmup", series_order=2, rrs_benchmark="Getting Started",
         space_required="Small area", position_primary="", presenter_id="",
         tags="warmup|physical|agility|movement|dynamic", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="WARM_003", drill_name="First Touch Activation", category="Warmup",
         description="Using a wall or rebounder, serve yourself balls at different heights and angles. Control each one cleanly. Alternate: inside of foot, outside of foot, chest, thigh. 3 sets of 10 touches per surface.",
         players_min=1, players_max=1, duration_minutes=8, field_type="Any",
         setup_data="Stand 5 yards from a wall. Throw ball against wall and receive each return.", equipment="Ball",
         coaching_points="Get your body behind the ball before it arrives. Soft landing on contact.",
         difficulty="beginner", intensity="low", coach_rating=5,
         solo_possible=True, min_equipment="Ball only",
         game_application="Your first touch in a game determines whether you stay on the ball or lose it immediately.",
         coaching_cues="Read the flight early|Get body behind the ball|Soft landing|Touch into space not under feet|Head up after controlling",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Foundation Warmup", series_order=3, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="first touch|warmup|receiving|wall work|technical", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="WARM_004", drill_name="Cone Dribbling Activation", category="Warmup",
         description="Set 6 cones in a straight line, 1 yard apart. Dribble through at walking pace first, then jogging, then 75%. Inside of foot, outside, then alternate. 3 lengths each way.",
         players_min=1, players_max=1, duration_minutes=8, field_type="Any",
         setup_data="6 cones 1 yard apart in a straight line - 6 yards total.", equipment="Ball, Cones",
         coaching_points="Head up between cones. Small touches - do not let ball get ahead of you.",
         difficulty="beginner", intensity="low", coach_rating=4,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="Close control in tight spaces. Every time you receive in traffic in a match you need this coordination.",
         coaching_cues="Small touches between cones|Eyes up between gates|Use inside and outside|Stay low|Accelerate on last cone",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Foundation Warmup", series_order=4, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="dribbling|warmup|close control|cones|activation", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="WARM_005", drill_name="Hip Mobility Circuit", category="Warmup",
         description="Complete before every session: leg swings front-back 10 each leg, leg swings side-to-side 10 each leg, hip circles 10 each direction, walking lunges with rotation 10 meters, ankle circles 10 each foot.",
         players_min=1, players_max=20, duration_minutes=8, field_type="Any",
         setup_data="No equipment needed. Stand in place or walk 10 meters.", equipment="",
         coaching_points="Go through the full range of motion. Do not rush. These prepare your joints, not just your muscles.",
         difficulty="beginner", intensity="low", coach_rating=4,
         solo_possible=True, min_equipment="Ball only",
         game_application="Hip mobility directly affects your ability to change direction, receive with different surfaces, and strike the ball with full power.",
         coaching_cues="Full range on every movement|Controlled speed|Engage core on lunges|Ankle circles both directions|Breathing stays relaxed",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Foundation Warmup", series_order=5, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="mobility|flexibility|warmup|physical|no equipment|hip", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="WARM_006", drill_name="Wall Passing Warmup", category="Warmup",
         description="Stand 5 yards from a wall. Pass with inside of right foot, receive with left. Build pace over 3 minutes. Switch: left foot passes, right receives. Finish with 1 minute alternating quick touches.",
         players_min=1, players_max=1, duration_minutes=8, field_type="Any",
         setup_data="Flat wall or rebounder 5 yards away. Mark standing position with cone.", equipment="Ball",
         coaching_points="Striking foot stays locked on every contact. Hip opens toward the wall as you pass.",
         difficulty="beginner", intensity="low", coach_rating=5,
         solo_possible=True, min_equipment="Ball only",
         game_application="Quick passing in pairs or triangles feels effortless when feet are warm and the strike is consistent.",
         coaching_cues="Locked ankle on every contact|Hip opens toward target|Firm pass not soft|Receive across body to other foot|Head up as pace increases",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Foundation Warmup", series_order=6, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="passing|warmup|wall work|both feet|activation", beta_ready=True, age_group_min=10, age_group_max=18),

    # TECHNICAL
    dict(drill_id="TECH_001", drill_name="Ball Mastery - 10 Core Patterns", category="Technical",
         description="Master 10 individual patterns, 60 seconds each: toe taps, inside-outside right foot, inside-outside left foot, sole rolls left-right, scissors, V-pull, L-pull turn, step-over, inside cut, outside cut. Clean execution at slow pace before adding speed.",
         players_min=1, players_max=1, duration_minutes=12, field_type="Any",
         setup_data="Stand in place or a 2x2 yard area. Ball only.", equipment="Ball",
         coaching_points="Quality over speed. Once clean at slow pace, add pace. Eyes up on every pattern.",
         difficulty="beginner", intensity="low", coach_rating=5,
         solo_possible=True, min_equipment="Ball only",
         game_application="Players who master these patterns use them in matches without thinking, freeing mental space to read the game.",
         coaching_cues="Quality before speed|Stay on toes throughout|Both feet equally|Eyes up as each pattern feels natural|Relax - tension reduces touch quality",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Foundation Technical", series_order=1, rrs_benchmark="Recreational Player",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="ball mastery|dribbling|individual|both feet|technical", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="TECH_002", drill_name="First Touch - Inside, Outside, Chest", category="Technical",
         description="Using a wall, work through 3 receiving surfaces. Set 1: serve against wall, receive inside of foot, redirect 45 degrees left. Set 2: outside of foot redirect. Set 3: throw, receive chest, drop to feet. 20 reps each set, both feet.",
         players_min=1, players_max=1, duration_minutes=12, field_type="Any",
         setup_data="5 yards from a wall. Mark a 45-degree target with a cone on each side.", equipment="Ball",
         coaching_points="The moment of contact: relax the receiving surface. Redirect into space - do not just stop the ball.",
         difficulty="beginner", intensity="low", coach_rating=5,
         solo_possible=True, min_equipment="Ball only",
         game_application="Your first touch either opens up your next action or kills it. A well-directed first touch puts the ball in space and you in motion.",
         coaching_cues="Soft surface on contact|Redirect into space not under feet|Body shape before ball arrives|Head up after touch|Touch takes you away from pressure",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Foundation Technical", series_order=2, rrs_benchmark="Recreational Player",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="first touch|receiving|wall work|technical|both feet", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="TECH_003", drill_name="Weak Foot Development", category="Technical",
         description="Full 15-minute session using only your weaker foot. Phase 1 (5 min): ball mastery - toe taps, inside-outside, sole rolls. Phase 2 (5 min): passing to wall from 10 yards. Phase 3 (5 min): dribble through cone gates. No strong foot allowed.",
         players_min=1, players_max=1, duration_minutes=15, field_type="Any",
         setup_data="Ball, 4 cones for a small gate, wall for passing phase.", equipment="Ball, Cones",
         coaching_points="Ankle stays locked even when it does not feel natural. Repetition builds the coordination that makes it feel normal.",
         difficulty="intermediate", intensity="medium", coach_rating=5,
         solo_possible=True, min_equipment="Ball only",
         game_application="Two-footed players are unpredictable because defenders cannot show them one way. Every weak foot rep removes a defensive tool from your opponent.",
         coaching_cues="Ankle locked even when unnatural|Do not cheat to strong foot|Discomfort means it is working|Same technique as strong foot|Quality not quantity early",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Weak Foot Program", series_order=1, rrs_benchmark="Club Level",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="weak foot|both feet|dribbling|passing|technical", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="TECH_004", drill_name="Passing Accuracy to Wall Targets", category="Technical",
         description="Mark 3 targets on a wall at ground level: left, center, right - each 1 yard wide. From 10 yards, pass to each target 10 times with right then left foot. Move back to 15 yards and repeat. Aim for 8/10 accuracy.",
         players_min=1, players_max=1, duration_minutes=12, field_type="Any",
         setup_data="3 targets marked on a wall each 1 yard wide. Stand 10 then 15 yards away.", equipment="Ball",
         coaching_points="Non-kicking foot points at the target. Follow through toward target.",
         difficulty="beginner", intensity="low", coach_rating=4,
         solo_possible=True, min_equipment="Ball only",
         game_application="Every pass in a game is a targeting exercise. Training accuracy at range teaches your body the adjustments that produce a precise pass under pressure.",
         coaching_cues="Non-kicking foot beside ball pointing at target|Hip opens to target before strike|Follow through toward target|Locked ankle firm contact|Head down through the strike",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Foundation Technical", series_order=3, rrs_benchmark="Recreational Player",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="passing|accuracy|wall work|both feet|technical", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="TECH_005", drill_name="Dribbling Agility Course", category="Technical",
         description="8 cones in a straight line 1 yard apart. Run 1: inside right foot. Run 2: outside right foot. Run 3: alternate inside-outside. Run 4: left foot only. Run 5: 100% pace. Rest 30 seconds between runs. 5 complete sets.",
         players_min=1, players_max=1, duration_minutes=12, field_type="Any",
         setup_data="8 cones 1 yard apart, 8 yards total length.", equipment="Ball, Cones",
         coaching_points="Touch before each cone not after. As pace increases touches get smaller not larger.",
         difficulty="intermediate", intensity="medium", coach_rating=4,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="Carrying the ball at pace through a tight space uses exactly the coordination this drill builds.",
         coaching_cues="Touch before the cone not after|Head up every 2 cones|Body low at pace|Touches smaller as speed increases|Explode out of last cone",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Foundation Technical", series_order=4, rrs_benchmark="Club Level",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="dribbling|agility|cones|close control|technical", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="TECH_006", drill_name="Shooting Technique - Placed Finish", category="Technical",
         description="3 cone positions: right of center (12 yards), center (12 yards), left of center (12 yards). From each position, 5 placed finishes to the far post - low across the goalkeeper. Placement not power. 3 sets from each position.",
         players_min=1, players_max=1, duration_minutes=12, field_type="Any",
         setup_data="One goal or target. Three cone positions 12 yards out.", equipment="Ball, Goal",
         coaching_points="Plant foot beside the ball pointing at target. Keep head down through contact.",
         difficulty="intermediate", intensity="medium", coach_rating=5,
         solo_possible=True, min_equipment="Ball + Goals",
         game_application="Most goals are missed not because of the shot but because of the setup. This drill isolates technique so it becomes automatic under pressure.",
         coaching_cues="Plant foot beside ball pointing at target|Head stays down through contact|Strike middle to lower half|Follow through toward far post|Breathe - do not rush the setup",
         position_relevance="Striker|Winger|Attacking Midfielder",
         skill_category="Technical", drill_type="Isolation",
         series_name="Finishing", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="Striker", presenter_id="UNLV-01",
         tags="shooting|finishing|technical|goal|placed finish|striker|winger", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="TECH_007", drill_name="1v1 Attacking - Read the Defender", category="Technical",
         description="You vs one passive defender. Receive ball 15 yards from goal. Defender stands 5 yards in front showing you one way. Read their body shape, execute the right move (cut inside or go wide), get a shot or cross off. Passive defender - no tackling. 10 reps each side.",
         players_min=2, players_max=2, duration_minutes=12, field_type="Any",
         setup_data="Two cones as gate 15 yards from goal. Passive defender between you and goal.", equipment="Ball, Cones",
         coaching_points="Read the defender before you receive. The decision should be made before the touch not after.",
         difficulty="intermediate", intensity="medium", coach_rating=5,
         solo_possible=False, min_equipment="Ball + Partner",
         game_application="Every attacking 1v1 starts with reading the defender's shape. Players who decide before receiving create options. Players who decide after get caught.",
         coaching_cues="Read defender before ball arrives|Decision before first touch|Accelerate through the move|Use outside of foot for pace|Eyes on target after beating defender",
         position_relevance="Winger|Striker|Attacking Midfielder",
         skill_category="1v1", drill_type="Pressure",
         series_name="1v1 Development", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="Winger", presenter_id="UNLV-01",
         tags="1v1|attacking|dribbling|decision making|winger|striker", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="TECH_008", drill_name="Receiving and Turning - Four Directions", category="Technical",
         description="Partner serves to your feet from 10 yards. Receive and turn in one of four directions: inside right foot (open right), outside right foot (cut left), inside left foot (open left), sole pull (back). Partner calls direction just before serving. 5 reps each direction.",
         players_min=2, players_max=2, duration_minutes=12, field_type="Any",
         setup_data="Two players 10 yards apart. Can also use a wall.", equipment="Ball",
         coaching_points="Half-turned body shape before the ball arrives. Do not wait until ball is at feet to decide direction.",
         difficulty="intermediate", intensity="medium", coach_rating=5,
         solo_possible=False, min_equipment="Ball + Partner",
         game_application="The midfielder who can receive and turn quickly is the most dangerous player on the field. Every time you break a press it starts with this skill.",
         coaching_cues="Half-turned before ball arrives|Read direction before touch|First touch takes you away from pressure|Weight shifts to front foot immediately|Scan before receiving",
         position_relevance="Central Midfielder|Attacking Midfielder|Defensive Midfielder",
         skill_category="Technical", drill_type="Pressure",
         series_name="Midfield Technical", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="Central Midfielder", presenter_id="KC-01",
         tags="receiving|turning|first touch|midfielder|technical", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="TECH_009", drill_name="Crossing Technique - Three Deliveries", category="Technical",
         description="From a wide cone position 25 yards from goal, practice three deliveries: low driven near post (stays under 2 feet), whipped far post (curls away from goalkeeper), cutback to penalty spot. 8 reps each delivery, both feet.",
         players_min=1, players_max=1, duration_minutes=12, field_type="Any",
         setup_data="Cone at crossing position. Mark near post, far post, and penalty spot with cones.", equipment="Ball, Cones",
         coaching_points="Approach angle is everything. Plant foot beside the ball not in front.",
         difficulty="intermediate", intensity="medium", coach_rating=4,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="A winger who delivers three different crosses from the same position keeps defenders and the goalkeeper guessing.",
         coaching_cues="Approach from slight angle|Plant foot beside ball not in front|Ankle locked foot open for whipped delivery|Follow through across body for swing|Decide cross before last touch",
         position_relevance="Winger|Full Back",
         skill_category="Technical", drill_type="Isolation",
         series_name="Winger Technical", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="Winger", presenter_id="UNLV-01",
         tags="crossing|delivery|winger|technical|full back", beta_ready=True, age_group_min=12, age_group_max=18),

    # TACTICAL
    dict(drill_id="TACT_001", drill_name="Receiving Under Pressure - Back to Goal", category="Tactical",
         description="Partner passes to you from 10 yards. Passive defender presses from behind (no tackling). Options: hold and lay off to a third cone position, or shield and turn if defender commits. 15 reps then switch roles.",
         players_min=2, players_max=2, duration_minutes=12, field_type="Any",
         setup_data="Three cones: server, receiver, layoff target. Defender starts behind receiver.", equipment="Ball, Cones",
         coaching_points="Low center of gravity. Use arms and body legally to protect. Feel where defender is before ball arrives.",
         difficulty="intermediate", intensity="medium", coach_rating=5,
         solo_possible=False, min_equipment="Ball + Partner",
         game_application="Strikers and midfielders who can hold the ball under pressure bring the team up the field and buy time for teammates to join.",
         coaching_cues="Feel defender before ball arrives|Low center of gravity - wide base|Use arms within the rules|Decide hold or turn before ball arrives|Layoff must be firm and accurate",
         position_relevance="Striker|Central Midfielder|Attacking Midfielder",
         skill_category="Tactical", drill_type="Pressure",
         series_name="Receiving Under Pressure", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="Striker", presenter_id="UNLV-01",
         tags="receiving|hold up play|tactical|pressure|striker|midfielder", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="TACT_002", drill_name="Pressing Angle and Cover Shadow", category="Tactical",
         description="4 cones: ball position (center), two passing targets (left and right), goal behind the ball. From 8 yards, sprint toward the ball on an angle that closes off the easier passing lane. Walk back, press closing the other lane. 10 reps alternating.",
         players_min=1, players_max=1, duration_minutes=10, field_type="Any",
         setup_data="4 cones: ball position, 2 targets 4 yards each side, goal behind. All within 15 yards.", equipment="Cones",
         coaching_points="You are not running straight at the ball. You are angling to cut off the easiest pass.",
         difficulty="intermediate", intensity="medium", coach_rating=4,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="Every time you press in a game your approach angle determines whether you win the ball, force a mistake, or get bypassed.",
         coaching_cues="Angle cuts the easiest pass|Body shape blocks the lane on arrival|Do not go to ground early|Stay on feet - stay a threat|React immediately if they play the other way",
         position_relevance="Winger|Striker|Central Midfielder",
         skill_category="Tactical", drill_type="Isolation",
         series_name="Pressing", series_order=1, rrs_benchmark="Varsity Starter",
         space_required="Small area", position_primary="", presenter_id="UNLV-01",
         tags="pressing|defensive|tactical|winger|striker|midfielder", beta_ready=True, age_group_min=13, age_group_max=18),
    dict(drill_id="TACT_003", drill_name="Playing Out Under Press - Decision Drill", category="Tactical",
         description="5 cones: your position, two short passing options (5 yards each side), two long options (15 yards each side). Partner calls which option is open just as you prepare to play. Execute that pass within 2 seconds. 20 reps at increasing speed.",
         players_min=1, players_max=2, duration_minutes=10, field_type="Any",
         setup_data="5 cones representing 4 passing options. Partner calls the target. Solo: number cones and use dice.", equipment="Ball, Cones",
         coaching_points="Scan before the ball arrives so you already know your options. Decision made before pressure arrives.",
         difficulty="advanced", intensity="medium", coach_rating=5,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="Playing out under a high press separates modern technical defenders from reactive ones.",
         coaching_cues="Scan before receiving - know your options|Decision made before ball arrives|Accurate weight - not just right direction|Communicate with partner|React immediately - no pause",
         position_relevance="Center Back|Full Back|Defensive Midfielder|Goalkeeper",
         skill_category="Tactical", drill_type="Pressure",
         series_name="Playing Out From the Back", series_order=1, rrs_benchmark="Varsity Starter",
         space_required="Small area", position_primary="Center Back", presenter_id="KC-01",
         tags="playing out|tactical|center back|goalkeeper|decision making|pressing", beta_ready=True, age_group_min=13, age_group_max=18),
    dict(drill_id="TACT_004", drill_name="Checking Movement - Drop and Spin", category="Tactical",
         description="3 cones in a line: back space (10 yards), start position, front check (5 yards). Rep 1: sprint to front cone, receive imaginary pass, immediately spin toward back cone. Rep 2: jog to front, stop, push off and sprint to back cone (dummy check). 15 reps alternating.",
         players_min=1, players_max=1, duration_minutes=10, field_type="Any",
         setup_data="3 cones in a line: back space 10y, start position, front check 5y.", equipment="Cones",
         coaching_points="Quality of the check-in determines the space you create behind. An explosive check forces the defender's decision.",
         difficulty="intermediate", intensity="medium", coach_rating=4,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="The best players are not just running to get the ball - they are moving to create space for themselves or teammates.",
         coaching_cues="Explosive change of direction - sell the fake|Stay on toes throughout|Check defender's position before dropping|Spin to back only if defender steps|Arms drive the change",
         position_relevance="Striker|Attacking Midfielder|Winger|Central Midfielder",
         skill_category="Tactical", drill_type="Isolation",
         series_name="Movement Off the Ball", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="Striker", presenter_id="UNLV-01",
         tags="movement|off the ball|tactical|striker|runs|checking", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="TACT_005", drill_name="Defensive Positioning - Jockeying", category="Tactical",
         description="Partner dribbles slowly toward you from 10 yards. Get into defensive stance (side-on, weight forward) and jockey backward at the same pace, forcing them one way. Do not dive in. 20 reps - alternate which side you show them.",
         players_min=2, players_max=2, duration_minutes=10, field_type="Any",
         setup_data="Two players 10 yards apart. 15-yard channel marked with cones.", equipment="Ball, Cones",
         coaching_points="Side-on body shape - never square on. Stay 1-2 yards from attacker: close enough to engage, far enough to react.",
         difficulty="intermediate", intensity="medium", coach_rating=5,
         solo_possible=False, min_equipment="Ball + Partner",
         game_application="Defenders who dive in get beaten every time. Defenders who jockey control the attacker's options and win the ball cleanly.",
         coaching_cues="Side-on body shape - never square|Stay 1-2 yards from attacker|Weight forward on front foot|Read attacker's hips not feet|Wait for touch too big then engage",
         position_relevance="Center Back|Full Back|Defensive Midfielder",
         skill_category="1v1", drill_type="Pressure",
         series_name="1v1 Defending", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="Center Back", presenter_id="KC-01",
         tags="defending|jockeying|1v1|tactical|center back|full back", beta_ready=True, age_group_min=12, age_group_max=18),

    # PHYSICAL
    dict(drill_id="COND_001", drill_name="Change of Direction Speed - T-Drill", category="Physical",
         description="T-shape with 4 cones: start, center (5 yards ahead), left and right arms (5 yards each way from center). Sprint to center, shuffle left (touch cone), shuffle right 10 yards (touch cone), shuffle back to center, backpedal to start. Rest 60 seconds. 8 reps.",
         players_min=1, players_max=1, duration_minutes=12, field_type="Any",
         setup_data="T-shape: start cone, 5 yards to center, 5 yards each way for the arms.", equipment="Cones",
         coaching_points="Never cross your feet on lateral shuffle. Touch the cone. Explosive out of every change.",
         difficulty="intermediate", intensity="high", coach_rating=4,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="The ability to change direction explosively separates fast players from effective players.",
         coaching_cues="Stay low through direction changes|Never cross feet on lateral shuffle|Touch the cone|Explosive first step from every stop|Arms drive the change",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Speed and Agility", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="", presenter_id="",
         tags="agility|speed|change of direction|physical|t-drill", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="COND_002", drill_name="Explosive Acceleration with Ball", category="Physical",
         description="Cones at 10, 15, and 20 yards. Reps 1-3: sprint to each distance without ball. Reps 4-6: same distances dribbling a ball with close control at full speed. Rest 45 seconds between reps. 3 sets.",
         players_min=1, players_max=1, duration_minutes=12, field_type="Any",
         setup_data="3 cones at 10, 15, 20 yards from start. Ball for reps 4-6.", equipment="Ball, Cones",
         coaching_points="First step is everything. Drive the knee forward. On ball reps, first touch sets the sprint distance.",
         difficulty="intermediate", intensity="high", coach_rating=4,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="The first 10 yards of any run decides games - breakaways, recovery runs, pressing triggers. Most players train distance. Train acceleration.",
         coaching_cues="Forward lean at start|Drive knee forward|Arms pump hard for first 5 steps|On ball: first touch sets the pace|Decelerate under control",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Speed and Agility", series_order=2, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="", presenter_id="",
         tags="speed|acceleration|explosive|physical|with ball", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="COND_003", drill_name="Lateral Quickness Pattern", category="Physical",
         description="5 cones in a line 1 yard apart. Facing the line, shuffle-step touch each cone and back. Then two-step pattern: right foot left foot between each cone, down and back. 4 sets of each pattern, 30 seconds rest.",
         players_min=1, players_max=1, duration_minutes=10, field_type="Any",
         setup_data="5 cones 1 yard apart in a line - 5 yards total.", equipment="Cones",
         coaching_points="Stay low - do not stand up between touches. Quick ground contact. No pause at each cone.",
         difficulty="intermediate", intensity="high", coach_rating=4,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="Lateral quickness determines how well you hold defensive shape, track wide runners, and recover position.",
         coaching_cues="Stay low - do not bounce|Quick ground contact|No crossing of feet|Eyes forward throughout|Each rep faster than last",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Speed and Agility", series_order=3, rrs_benchmark="Club Level",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="lateral|quickness|agility|physical|footwork", beta_ready=True, age_group_min=11, age_group_max=18),
    dict(drill_id="COND_004", drill_name="Interval Conditioning with Ball", category="Physical",
         description="2 cones 25 yards apart. Work: dribble at 80% from cone to cone, quick turn (sole or V-pull), dribble back. Rest: walk without ball. 1:1 work-to-rest ratio. 12 working reps. Increase pace every 4 reps.",
         players_min=1, players_max=1, duration_minutes=15, field_type="Any",
         setup_data="2 cones 25 yards apart. Ball.", equipment="Ball, Cones",
         coaching_points="Keep ball within 2 yards even at conditioning pace. This is not sprint-and-chase.",
         difficulty="intermediate", intensity="high", coach_rating=3,
         solo_possible=True, min_equipment="Ball + Cones",
         game_application="Soccer demands ball control while working at high intensity. Training them together bridges the gap between isolated technique and match performance.",
         coaching_cues="Ball within 2 yards at all times|Quick clean turn at each cone|Maintain pace - no drop-off|Controlled breathing|Last 3 reps at 90%",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Conditioning", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="", presenter_id="",
         tags="conditioning|interval|fitness|with ball|physical", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="COND_005", drill_name="Balance and Core - Single Leg Ball Control", category="Physical",
         description="Stand on one leg. Juggle the ball 10 times without the standing foot leaving the ground. Switch legs. Progress: juggle 10 times on right leg, receive a thrown ball on same leg, control to foot without switching. 5 sets each leg.",
         players_min=1, players_max=1, duration_minutes=10, field_type="Any",
         setup_data="Stand in place. Ball only.", equipment="Ball",
         coaching_points="Engage your core before each rep. Standing leg slightly bent - never locked.",
         difficulty="intermediate", intensity="low", coach_rating=4,
         solo_possible=True, min_equipment="Ball only",
         game_application="Single-leg balance is the foundation of every kick, every landing from a jump, and every cut.",
         coaching_cues="Core engaged before each rep|Slight bend in standing knee|Ankle controls balance - let it move|Eyes on the ball|Reset if you lose it - do not rush",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Conditioning", series_order=2, rrs_benchmark="Recreational Player",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="balance|core|juggling|physical|single leg", beta_ready=True, age_group_min=10, age_group_max=18),

    # GAME APPLICATION
    dict(drill_id="SSG_001", drill_name="1v1 to Small Goal - Full Speed", category="Game Application",
         description="Two small cone goals (2 yards wide) 20 yards apart. Server feeds ball to attacker who has a 1v1 to finish. If defender wins the ball they attack the opposite goal. 10 rounds each as attacker.",
         players_min=2, players_max=2, duration_minutes=12, field_type="Any",
         setup_data="2 small goals 2 yards wide, 20 yards apart. Server at the side. 20x20 yard area.", equipment="Ball, Cones",
         coaching_points="This is game speed - no passive defending. Attacker must execute under real pressure.",
         difficulty="advanced", intensity="high", coach_rating=5,
         solo_possible=False, min_equipment="Ball + Partner",
         game_application="The 1v1 is the most fundamental game situation in soccer. Everything worked on this session gets tested at match speed.",
         coaching_cues="Attacker: be decisive - no hesitation|Use move that sets up your stronger foot|Accelerate after the move|Defender: side-on no diving|Compete at game intensity",
         position_relevance="Winger|Striker|Attacking Midfielder|Full Back|Center Back",
         skill_category="Game Application", drill_type="Game Application",
         series_name="Game Application", series_order=1, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="", presenter_id="",
         tags="1v1|game application|competitive|attacking|defending", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="SSG_002", drill_name="Finishing Under Pressure - Defender Closing", category="Game Application",
         description="Server plays ball to your feet from edge of box. Simultaneously a defender starts 8 yards away and sprints to close you. You have 1-2 touches to set and shoot before they arrive. 15 reps each finishing foot.",
         players_min=2, players_max=3, duration_minutes=12, field_type="Any",
         setup_data="Server at edge of box. Shooter 15 yards from goal. Defender 8 yards from shooter. One goal.", equipment="Ball, Goal",
         coaching_points="The pressure arrives just as you are shooting. Train yourself to get the shot off in the gap.",
         difficulty="advanced", intensity="high", coach_rating=5,
         solo_possible=False, min_equipment="Ball + Partner",
         game_application="Most goals in matches are scored with a defender closing. The striker who sets their feet quickly and shoots calmly under pressure scores.",
         coaching_cues="Shot off in 2 touches maximum|First touch sets the shot - commit|Do not wait for the defender|Head down on strike|Follow your shot for the rebound",
         position_relevance="Striker|Winger|Attacking Midfielder",
         skill_category="Game Application", drill_type="Game Application",
         series_name="Game Application", series_order=2, rrs_benchmark="Varsity Starter",
         space_required="Small area", position_primary="Striker", presenter_id="UNLV-01",
         tags="finishing|shooting|pressure|game application|striker", beta_ready=True, age_group_min=13, age_group_max=18),
    dict(drill_id="SSG_003", drill_name="Combination to Finish - Wall Pass", category="Game Application",
         description="You and a partner. You dribble toward the box edge. Partner makes a run to receive your pass (wall pass). You play to them, continue your run, receive the return, and finish. From left and right sides. 10 reps each side, alternate roles.",
         players_min=2, players_max=2, duration_minutes=12, field_type="Any",
         setup_data="Two players, a goal, open area 20 yards from goal. Focus on combination timing.", equipment="Ball, Goal",
         coaching_points="The run after the pass is the most important moment. Pass-and-move creates the goal.",
         difficulty="intermediate", intensity="high", coach_rating=5,
         solo_possible=False, min_equipment="Ball + Partner",
         game_application="The one-two combination is one of the most effective ways to break through a defensive line in a match.",
         coaching_cues="Pass-and-move - do not stop|Call for the return|Return pass weight firm into stride|Arrive onto ball with pace|Finish across your body",
         position_relevance="Winger|Striker|Attacking Midfielder|Central Midfielder",
         skill_category="Game Application", drill_type="Game Application",
         series_name="Game Application", series_order=3, rrs_benchmark="Club Level",
         space_required="Small area", position_primary="", presenter_id="UNLV-01",
         tags="combination play|wall pass|finishing|game application", beta_ready=True, age_group_min=12, age_group_max=18),
    dict(drill_id="SSG_004", drill_name="Switch of Play - Receive Wide and Deliver", category="Game Application",
         description="Server plays a long diagonal to you wide. Control with first touch moving forward, set in one touch, and deliver: rep 1 low near post driven; rep 2 whipped far post; rep 3 cutback to penalty spot. Partner arrives at each target. 5 reps each delivery.",
         players_min=2, players_max=3, duration_minutes=12, field_type="Any",
         setup_data="Server in center, wide player on wing, arriving runner at box. Simulate a switch of play.", equipment="Ball, Cones, Goal",
         coaching_points="First touch moves you forward - do not stop the ball. Switch is only effective if you receive and deliver quickly.",
         difficulty="advanced", intensity="high", coach_rating=4,
         solo_possible=False, min_equipment="Ball + Partner",
         game_application="Teams press one side - the switch is the escape route. The winger who controls and delivers quickly turns a defensive moment into a scoring chance.",
         coaching_cues="First touch forward - open body|Set delivery in one touch|Communicate with arriving runner|Delivery away from goalkeeper|Pace matches the runner",
         position_relevance="Winger|Full Back",
         skill_category="Game Application", drill_type="Game Application",
         series_name="Game Application", series_order=4, rrs_benchmark="Varsity Starter",
         space_required="Half pitch", position_primary="Winger", presenter_id="UNLV-01",
         tags="switch of play|crossing|winger|full back|game application", beta_ready=True, age_group_min=13, age_group_max=18),
    dict(drill_id="SSG_005", drill_name="GK Distribution Under Press", category="Game Application",
         description="GK starts with ball. 3 cone targets: short CB left (8 yards), short CB right (8 yards), long forward (25 yards). Pressing partner closes from 15 yards on signal. Distribute to the called target before they arrive. 15 reps, mix of targets.",
         players_min=2, players_max=2, duration_minutes=12, field_type="Any",
         setup_data="GK in goal area. 3 cone targets at 8y left, 8y right, 25y forward. Presser starts 15y away.", equipment="Ball, Cones",
         coaching_points="Scan before picking up the ball. Identify target before presser arrives. Decision 2 seconds before execution.",
         difficulty="advanced", intensity="high", coach_rating=5,
         solo_possible=False, min_equipment="Ball + Partner",
         game_application="Every high press tests the goalkeeper's ability to play out under pressure. A goalkeeper who reads the press and distributes accurately is worth more than any single defensive action.",
         coaching_cues="Scan before picking ball up|Decision before presser is within 5 yards|Accurate weight - not just right direction|If short blocked go long immediately|Call the target as you play",
         position_relevance="Goalkeeper",
         skill_category="Game Application", drill_type="Game Application",
         series_name="GK Game Application", series_order=1, rrs_benchmark="Varsity Starter",
         space_required="Small area", position_primary="Goalkeeper", presenter_id="YOU-01",
         tags="goalkeeper|distribution|pressing|game application|playing out", beta_ready=True, age_group_min=13, age_group_max=18),

    # COOL DOWN
    dict(drill_id="COOL_001", drill_name="Static Stretching Routine", category="Cool Down",
         description="Hold each stretch 30 seconds both sides: standing quad, standing hamstring (toe touch), hip flexor lunge, groin butterfly, calf against wall, shoulder cross-body, seated IT band. Total 10 minutes.",
         players_min=1, players_max=20, duration_minutes=10, field_type="Any",
         setup_data="No equipment. Space to sit and stand.", equipment="",
         coaching_points="Hold, do not bounce. Breathe into each stretch. Recovery is training.",
         difficulty="beginner", intensity="low", coach_rating=5,
         solo_possible=True, min_equipment="Ball only",
         game_application="Players who skip the cooldown stretch consistently get injured more. 10 minutes here can mean the difference between being available for the next match.",
         coaching_cues="Hold - do not bounce|Breathe into stretch|Feel tension release|Both sides equally|Do not rush - this is recovery time",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Cool Down", series_order=1, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="cooldown|stretching|flexibility|recovery|physical", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="COOL_002", drill_name="Light Ball Mastery Cooldown", category="Cool Down",
         description="5 minutes of slow relaxed ball mastery to gradually lower heart rate. Toe taps at 30% pace, sole rolls, light inside-outside, casual juggling. No pressure, no targets.",
         players_min=1, players_max=1, duration_minutes=5, field_type="Any",
         setup_data="Ball only. Stand in place.", equipment="Ball",
         coaching_points="This is active recovery not drill practice. The goal is to bring your heart rate down while keeping feet active.",
         difficulty="beginner", intensity="low", coach_rating=4,
         solo_possible=True, min_equipment="Ball only",
         game_application="Ending every session with a ball at your feet reinforces good touch even when tired. This is the state you are in at the 85th minute of a match.",
         coaching_cues="No pressure - this is enjoyment time|Keep it slow and relaxed|Use both feet naturally|Let breathing return to normal|Reflect on what went well today",
         position_relevance="", skill_category="Technical", drill_type="Isolation",
         series_name="Cool Down", series_order=2, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="cooldown|ball mastery|recovery|relaxed|active recovery", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="COOL_003", drill_name="Hip and Hamstring Recovery Routine", category="Cool Down",
         description="Seated and lying recovery circuit: seated hamstring stretch 30s each leg, lying glute pull 30s each, lying figure-4 hip stretch 30s each side, pigeon pose 60s each side. Repeat full circuit twice.",
         players_min=1, players_max=20, duration_minutes=10, field_type="Any",
         setup_data="Flat surface to lie on. No equipment.", equipment="",
         coaching_points="Hamstrings and hip flexors are the two areas that get tightest in soccer. Consistent work here prevents the strains that take players out for weeks.",
         difficulty="beginner", intensity="low", coach_rating=5,
         solo_possible=True, min_equipment="Ball only",
         game_application="Hamstring and hip flexibility directly affects sprint mechanics, shooting power, and lateral movement.",
         coaching_cues="Breathe - do not hold your breath|Feel the stretch not pain|Both sides equal time|Pigeon pose is uncomfortable - that is normal|Improvement takes weeks - be consistent",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Cool Down", series_order=3, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="cooldown|flexibility|hip|hamstring|recovery", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="COOL_004", drill_name="Foam Rolling Recovery", category="Cool Down",
         description="60 seconds each area: quads (both legs), IT band (both sides), calves (both legs), glutes (both sides), upper back. Move slowly. Pause and hold on tender spots for 10-15 seconds.",
         players_min=1, players_max=20, duration_minutes=10, field_type="Any",
         setup_data="Foam roller. Flat surface.", equipment="Foam roller",
         coaching_points="Go slowly. You are releasing tension in the fascia - this takes time. Do not roll your lower back.",
         difficulty="beginner", intensity="low", coach_rating=5,
         solo_possible=True, min_equipment="Ball only",
         game_application="Foam rolling reduces muscle soreness, improves recovery speed, and helps prevent overuse injuries.",
         coaching_cues="Slow rolls - do not race|Pause on tender spots and breathe|Do not roll over joints or bones|Keep core slightly engaged|Lower back - stretch instead of roll",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Cool Down", series_order=4, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="cooldown|foam rolling|recovery|physical|flexibility", beta_ready=True, age_group_min=10, age_group_max=18),
    dict(drill_id="COOL_005", drill_name="Breathing and Session Reflection", category="Cool Down",
         description="Walk slowly for 3 minutes, breathing deeply (inhale 4 counts, hold 2, exhale 6 counts). Then sit quietly for 2 minutes. Reflect on: one technical thing you did well today, one thing to improve next session, one moment you are proud of.",
         players_min=1, players_max=20, duration_minutes=5, field_type="Any",
         setup_data="No equipment. Quiet space.", equipment="",
         coaching_points="Mental recovery is as important as physical recovery. Players who reflect consistently improve faster.",
         difficulty="beginner", intensity="low", coach_rating=4,
         solo_possible=True, min_equipment="Ball only",
         game_application="The best players reflect on every session and every match. This habit done consistently over months is how average players become exceptional ones.",
         coaching_cues="Breathing 4-2-6: inhale hold exhale|Let mind slow with body|No phone for 5 minutes|One win one improvement one proud moment|This habit separates serious players",
         position_relevance="", skill_category="Physical", drill_type="Isolation",
         series_name="Cool Down", series_order=5, rrs_benchmark="Getting Started",
         space_required="Backyard", position_primary="", presenter_id="",
         tags="cooldown|mindset|breathing|reflection|mental", beta_ready=True, age_group_min=10, age_group_max=18),
]


from data_loader import DRILL_COLUMNS, DRILL_DEFAULTS

def build_row(d):
    row = dict(DRILL_DEFAULTS)
    for k, v in d.items():
        row[k] = v
    row["age_groups"]       = "U{}-U{}".format(d.get("age_group_min", 10), d.get("age_group_max", 18))
    row["status"]           = "Published"
    row["beta_ready"]       = d.get("beta_ready", True)
    row["solo_possible"]    = d.get("solo_possible", True)
    row["is_favorite"]      = False
    row["times_used"]       = 0
    row["last_used_date"]   = ""
    row["diagram_path"]     = ""
    row["diagram_metadata"] = ""
    row["diagram_url"]      = ""
    row["video_url"]        = ""
    row["video_youtube_url"]= ""
    row["video_url_short"]  = ""
    row["video_url_full"]   = ""
    row["video_thumbnail"]  = ""
    row["video_status"]     = "Not Filmed"
    row["filming_date"]     = ""
    row["filming_notes"]    = ""
    row["date_published"]   = ""
    row["slug"]             = d.get("drill_id", "").lower().replace("_", "-")
    return row


def main():
    rows = [build_row(d) for d in DRILLS]
    df = pd.DataFrame(rows)
    for col in DRILL_COLUMNS:
        if col not in df.columns:
            df[col] = DRILL_DEFAULTS.get(col, "")
    df = df[DRILL_COLUMNS]

    data_dir = ROOT / "data"
    targets = list(data_dir.glob("**/drill_library.csv"))

    print("Rebuilding drill library - {} individual player drills".format(len(DRILLS)))
    print("-" * 50)
    for path in targets:
        df.to_csv(path, index=False)
        print("  Written: {}  ({} drills)".format(path, len(df)))

    print("-" * 50)
    by_cat = df.groupby("category").size().to_dict()
    for cat, count in sorted(by_cat.items()):
        solo_count = int(df[df["category"] == cat]["solo_possible"].sum())
        print("  {:<25} {} drills  ({} solo-possible)".format(cat, count, solo_count))
    print("\n  Total drills: {}".format(len(df)))
    solo_total = int(df["solo_possible"].sum())
    print("  Solo-possible: {}".format(solo_total))
    print("  Requires partner: {}".format(len(df) - solo_total))


if __name__ == "__main__":
    main()
